### ISSUE TITLE
Missing link to OpenImages50 model 

### ISSUE THREAD

**Issue by sabraha2** [JudyYe/shelf-sup-mesh#2]
Hi, thank you for sharing your great work! :) 

The link to the OpenImages50 weights lead to a 404 error page and was wondering if these weights were accessible or if they were posted elsewhere. 

Thanks!

**Comment by JudyYe** [comment]
Hi, sorry about that,

I updated link to models [here](https://drive.google.com/file/d/1BOIcPRXdpKPNi6G3pjDSkyaKGCf5kMDm/view?usp=sharing).
